New realization is made. Read about error C2512.(Default constructor for Node struct was added to avoid this error). Debug algorithm git status./Dijkstra_algorithm.exe ../graphs/2.txt 5 0 Worked correctly from first execution - very suspicious